// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/docs/theming
//
// Provides React context for runtime theme switching.
// Wrap any subtree in <PdfxThemeProvider theme={myTheme}> to override the active theme.

/* eslint-disable react-refresh/only-export-components */
// This file intentionally exports both a component (PdfxThemeProvider) and hooks/context.
// All PDF components import from a single file — splitting would break the public API.

/* eslint-disable react-hooks/rules-of-hooks */
// react-hooks/rules-of-hooks: usePdfxTheme and useSafeMemo intentionally call hooks inside
// try/catch — the accepted pattern for libraries that support both React render and
// plain-function (unit-test) invocation.

import * as React from 'react';
import { type DependencyList, type ReactNode, createContext, useContext, useMemo } from 'react';
import { theme as defaultTheme } from './pdfx-theme';

type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

/**
 * Detect whether React currently has an active dispatcher.
 * When components are invoked as plain functions in tests, dispatcher is null.
 */
function hasActiveDispatcher(): boolean {
  const maybeInternals = React as unknown as {
    __CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE?: { H?: unknown };
  };

  const dispatcher =
    maybeInternals.__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE?.H;
  return dispatcher != null;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = useMemo(() => theme ?? defaultTheme, [theme]);
  return <PdfxThemeContext.Provider value={resolvedTheme}>{children}</PdfxThemeContext.Provider>;
}

/**
 * Regex patterns that indicate the hook was called outside a valid React context.
 * These errors should be caught and handled gracefully by falling back to defaults.
 */
const HOOK_ERROR_PATTERNS =
  /invalid hook call|useContext|useMemo|cannot read properties of null|dispatcher|renderWithHooks|resolveDispatcher|hooks can only be called|rendered fewer hooks/i;

/**
 * Returns the active PdfxTheme from context, or the default theme when called
 * outside a React render tree (e.g. unit tests).
 *
 * The try/catch is intentional: when components are invoked as plain functions
 * in unit tests, React's dispatcher is unavailable and useContext throws an
 * "Invalid hook call" error. We catch only that specific case and fall back to
 * defaultTheme. Any other error is re-thrown so real bugs are never swallowed.
 *
 * The eslint-disable is required because react-hooks/rules-of-hooks flags hooks
 * inside try/catch — this is the accepted pattern for libraries that must support
 * both React render and plain-function (test) invocation contexts.
 */
export function usePdfxTheme(): PdfxTheme {
  if (!hasActiveDispatcher()) {
    return defaultTheme;
  }

  try {
    return useContext(PdfxThemeContext);
  } catch (error) {
    // Suppress context errors when hook is called outside a render tree or
    // without a provider (common in unit tests). Re-throw anything else.
    if (error instanceof Error && HOOK_ERROR_PATTERNS.test(error.message)) {
      return defaultTheme;
    }
    throw error;
  }
}

/**
 * Memoises the result of factory(). Falls back to factory() directly when
 * called outside React (e.g. unit tests that invoke components as plain functions).
 *
 * Follows the same error-handling strategy as usePdfxTheme.
 */
export function useSafeMemo<T>(factory: () => T, deps: DependencyList): T {
  if (!hasActiveDispatcher()) {
    return factory();
  }

  try {
    return useMemo(factory, deps);
  } catch (error) {
    if (error instanceof Error && HOOK_ERROR_PATTERNS.test(error.message)) {
      return factory();
    }
    throw error;
  }
}
