packages:
  - apps/*
  - packages/*
  - configs

catalog:
  "@react-pdf/renderer": ^4.1.4
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.0.8
  react: ^19.2.4
  react-dom: ^19.0.0
  typescript: ^5.9.3
  vite: ^6.0.5
  vitest: ^2.1.8
