import type { PdfxTheme } from '@pdfx/shared';

/**
 * Generates a self-contained TypeScript theme file from a PdfxTheme preset.
 *
 * The generated file includes the full PdfxTheme type definition inline
 * so users have zero dependency on @pdfx/shared in their project.
 */
export function generateThemeFile(preset: PdfxTheme): string {
  return `// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/docs/theming
//
// All PDF components import this file for their styling tokens.
// Edit the values below to change the look of every component at once.

// ─── Theme Type ─────────────────────────────────────────────────────────────

interface PdfxTheme {
  name: string;
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: { regular: number; medium: number; semibold: number; bold: number };
    lineHeights: { tight: number; normal: number; relaxed: number };
    borderRadius: { none: number; sm: number; md: number; lg: number; full: number };
    letterSpacing: { tight: number; normal: number; wide: number; wider: number };
  };
  colors: {
    foreground: string;
    background: string;
    muted: string;
    mutedForeground: string;
    primary: string;
    primaryForeground: string;
    border: string;
    accent: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string;
      fontWeight: number;
      lineHeight: number;
      fontSize: { h1: number; h2: number; h3: number; h4: number; h5: number; h6: number };
    };
  };
  spacing: {
    page: { marginTop: number; marginRight: number; marginBottom: number; marginLeft: number };
    sectionGap: number;
    paragraphGap: number;
    componentGap: number;
  };
  page: {
    size: 'A4' | 'LETTER' | 'LEGAL';
    orientation: 'portrait' | 'landscape';
  };
}

// ─── Your Theme ─────────────────────────────────────────────────────────────

export const theme: PdfxTheme = ${serializeTheme(preset)};
`;
}

/** Serializes a PdfxTheme to formatted TypeScript source code */
function serializeTheme(t: PdfxTheme): string {
  return `{
  name: '${t.name}',

  // Raw design scales — the palette of available values
  primitives: {
    typography: {
      xs: ${t.primitives.typography.xs},
      sm: ${t.primitives.typography.sm},
      base: ${t.primitives.typography.base},
      lg: ${t.primitives.typography.lg},
      xl: ${t.primitives.typography.xl},
      '2xl': ${t.primitives.typography['2xl']},
      '3xl': ${t.primitives.typography['3xl']},
    },
    spacing: {
      0: ${t.primitives.spacing[0]},
      0.5: ${t.primitives.spacing[0.5]},
      1: ${t.primitives.spacing[1]},
      2: ${t.primitives.spacing[2]},
      3: ${t.primitives.spacing[3]},
      4: ${t.primitives.spacing[4]},
      5: ${t.primitives.spacing[5]},
      6: ${t.primitives.spacing[6]},
      8: ${t.primitives.spacing[8]},
      10: ${t.primitives.spacing[10]},
      12: ${t.primitives.spacing[12]},
      16: ${t.primitives.spacing[16]},
    },
    fontWeights: {
      regular: ${t.primitives.fontWeights.regular},
      medium: ${t.primitives.fontWeights.medium},
      semibold: ${t.primitives.fontWeights.semibold},
      bold: ${t.primitives.fontWeights.bold},
    },
    lineHeights: {
      tight: ${t.primitives.lineHeights.tight},
      normal: ${t.primitives.lineHeights.normal},
      relaxed: ${t.primitives.lineHeights.relaxed},
    },
    borderRadius: {
      none: ${t.primitives.borderRadius.none},
      sm: ${t.primitives.borderRadius.sm},
      md: ${t.primitives.borderRadius.md},
      lg: ${t.primitives.borderRadius.lg},
      full: ${t.primitives.borderRadius.full},
    },
    letterSpacing: {
      tight: ${t.primitives.letterSpacing.tight},
      normal: ${t.primitives.letterSpacing.normal},
      wide: ${t.primitives.letterSpacing.wide},
      wider: ${t.primitives.letterSpacing.wider},
    },
  },

  // Semantic colors — hex values, react-pdf compatible
  colors: {
    foreground: '${t.colors.foreground}',
    background: '${t.colors.background}',
    muted: '${t.colors.muted}',
    mutedForeground: '${t.colors.mutedForeground}',
    primary: '${t.colors.primary}',
    primaryForeground: '${t.colors.primaryForeground}',
    border: '${t.colors.border}',
    accent: '${t.colors.accent}',
    destructive: '${t.colors.destructive}',
    success: '${t.colors.success}',
    warning: '${t.colors.warning}',
    info: '${t.colors.info}',
  },

  // Typography — font families, sizes, weights, line heights
  typography: {
    body: {
      fontFamily: '${t.typography.body.fontFamily}',
      fontSize: ${t.typography.body.fontSize},
      lineHeight: ${t.typography.body.lineHeight},
    },
    heading: {
      fontFamily: '${t.typography.heading.fontFamily}',
      fontWeight: ${t.typography.heading.fontWeight},
      lineHeight: ${t.typography.heading.lineHeight},
      fontSize: {
        h1: ${t.typography.heading.fontSize.h1},
        h2: ${t.typography.heading.fontSize.h2},
        h3: ${t.typography.heading.fontSize.h3},
        h4: ${t.typography.heading.fontSize.h4},
        h5: ${t.typography.heading.fontSize.h5},
        h6: ${t.typography.heading.fontSize.h6},
      },
    },
  },

  // Spacing — page margins and gaps between elements
  spacing: {
    page: {
      marginTop: ${t.spacing.page.marginTop},
      marginRight: ${t.spacing.page.marginRight},
      marginBottom: ${t.spacing.page.marginBottom},
      marginLeft: ${t.spacing.page.marginLeft},
    },
    sectionGap: ${t.spacing.sectionGap},
    paragraphGap: ${t.spacing.paragraphGap},
    componentGap: ${t.spacing.componentGap},
  },

  // Page defaults
  page: {
    size: '${t.page.size}',
    orientation: '${t.page.orientation}',
  },
}`;
}

/**
 * Generates a self-contained pdfx-theme-context.tsx file.
 *
 * The file provides PdfxThemeContext, PdfxThemeProvider, usePdfxTheme, and
 * useSafeMemo — allowing runtime theme switching via <PdfxThemeProvider>.
 * It imports types from the sibling pdfx-theme.ts so it stays dependency-free.
 */
export function generateThemeContextFile(): string {
  return `// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/docs/theming
//
// Provides React context for runtime theme switching.
// Wrap any subtree in <PdfxThemeProvider theme={myTheme}> to override the active theme.

/* eslint-disable react-refresh/only-export-components */
// This file intentionally exports both a component (PdfxThemeProvider) and hooks/context.
// All PDF components import from a single file — splitting would break the public API.

import { type DependencyList, type ReactNode, createContext, useContext, useMemo } from 'react';
import { theme as defaultTheme } from './pdfx-theme';

type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = useMemo(() => theme ?? defaultTheme, [theme]);
  return <PdfxThemeContext.Provider value={resolvedTheme}>{children}</PdfxThemeContext.Provider>;
}

/**
 * Returns the active PdfxTheme from context, or the default theme when called
 * outside a React render tree (e.g. unit tests).
 *
 * The try/catch is intentional: when components are invoked as plain functions
 * in unit tests, React's dispatcher is unavailable and useContext throws an
 * "Invalid hook call" error. We catch only that specific case and fall back to
 * defaultTheme. Any other error is re-thrown so real bugs are never swallowed.
 *
 * The eslint-disable is required because react-hooks/rules-of-hooks flags hooks
 * inside try/catch — this is the accepted pattern for libraries that must support
 * both React render and plain-function (test) invocation contexts.
 */
export function usePdfxTheme(): PdfxTheme {
  try {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useContext(PdfxThemeContext);
  } catch (error) {
    // Only suppress React dispatcher errors ("Invalid hook call").
    // Re-throw anything else so unexpected bugs surface clearly.
    if (error instanceof Error && /invalid hook call/i.test(error.message)) {
      return defaultTheme;
    }
    throw error;
  }
}

/**
 * Memoises the result of factory(). Falls back to factory() directly when
 * called outside React (e.g. unit tests that invoke components as plain functions).
 *
 * Follows the same catch-narrowing strategy as usePdfxTheme.
 */
export function useSafeMemo<T>(factory: () => T, deps: DependencyList): T {
  try {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useMemo(factory, deps);
  } catch (error) {
    if (error instanceof Error && /invalid hook call/i.test(error.message)) {
      return factory();
    }
    throw error;
  }
}
`;
}
