import type { PdfxTheme } from '@pdfx/shared';

/**
 * Generates a self-contained TypeScript theme file from a PdfxTheme preset.
 *
 * The generated file includes the full PdfxTheme type definition inline
 * so users have zero dependency on @pdfx/shared in their project.
 */
export function generateThemeFile(preset: PdfxTheme): string {
  return `// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/docs/theming
//
// All PDF components import this file for their styling tokens.
// Edit the values below to change the look of every component at once.

// ─── Theme Type ─────────────────────────────────────────────────────────────

interface PdfxTheme {
  name: string;
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: { regular: number; medium: number; semibold: number; bold: number };
    lineHeights: { tight: number; normal: number; relaxed: number };
  };
  colors: {
    foreground: string;
    background: string;
    muted: string;
    mutedForeground: string;
    primary: string;
    primaryForeground: string;
    border: string;
    accent: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string;
      fontWeight: number;
      lineHeight: number;
      fontSize: { h1: number; h2: number; h3: number; h4: number; h5: number; h6: number };
    };
  };
  spacing: {
    page: { marginTop: number; marginRight: number; marginBottom: number; marginLeft: number };
    sectionGap: number;
    paragraphGap: number;
    componentGap: number;
  };
  page: {
    size: 'A4' | 'LETTER' | 'LEGAL';
    orientation: 'portrait' | 'landscape';
  };
}

// ─── Your Theme ─────────────────────────────────────────────────────────────

export const theme: PdfxTheme = ${serializeTheme(preset)};
`;
}

/** Serializes a PdfxTheme to formatted TypeScript source code */
function serializeTheme(t: PdfxTheme): string {
  return `{
  name: '${t.name}',

  // Raw design scales — the palette of available values
  primitives: {
    typography: {
      xs: ${t.primitives.typography.xs},
      sm: ${t.primitives.typography.sm},
      base: ${t.primitives.typography.base},
      lg: ${t.primitives.typography.lg},
      xl: ${t.primitives.typography.xl},
      '2xl': ${t.primitives.typography['2xl']},
      '3xl': ${t.primitives.typography['3xl']},
    },
    spacing: {
      0: ${t.primitives.spacing[0]},
      0.5: ${t.primitives.spacing[0.5]},
      1: ${t.primitives.spacing[1]},
      2: ${t.primitives.spacing[2]},
      3: ${t.primitives.spacing[3]},
      4: ${t.primitives.spacing[4]},
      5: ${t.primitives.spacing[5]},
      6: ${t.primitives.spacing[6]},
      8: ${t.primitives.spacing[8]},
      10: ${t.primitives.spacing[10]},
      12: ${t.primitives.spacing[12]},
      16: ${t.primitives.spacing[16]},
    },
    fontWeights: {
      regular: ${t.primitives.fontWeights.regular},
      medium: ${t.primitives.fontWeights.medium},
      semibold: ${t.primitives.fontWeights.semibold},
      bold: ${t.primitives.fontWeights.bold},
    },
    lineHeights: {
      tight: ${t.primitives.lineHeights.tight},
      normal: ${t.primitives.lineHeights.normal},
      relaxed: ${t.primitives.lineHeights.relaxed},
    },
  },

  // Semantic colors — hex values, react-pdf compatible
  colors: {
    foreground: '${t.colors.foreground}',
    background: '${t.colors.background}',
    muted: '${t.colors.muted}',
    mutedForeground: '${t.colors.mutedForeground}',
    primary: '${t.colors.primary}',
    primaryForeground: '${t.colors.primaryForeground}',
    border: '${t.colors.border}',
    accent: '${t.colors.accent}',
    destructive: '${t.colors.destructive}',
    success: '${t.colors.success}',
    warning: '${t.colors.warning}',
    info: '${t.colors.info}',
  },

  // Typography — font families, sizes, weights, line heights
  typography: {
    body: {
      fontFamily: '${t.typography.body.fontFamily}',
      fontSize: ${t.typography.body.fontSize},
      lineHeight: ${t.typography.body.lineHeight},
    },
    heading: {
      fontFamily: '${t.typography.heading.fontFamily}',
      fontWeight: ${t.typography.heading.fontWeight},
      lineHeight: ${t.typography.heading.lineHeight},
      fontSize: {
        h1: ${t.typography.heading.fontSize.h1},
        h2: ${t.typography.heading.fontSize.h2},
        h3: ${t.typography.heading.fontSize.h3},
        h4: ${t.typography.heading.fontSize.h4},
        h5: ${t.typography.heading.fontSize.h5},
        h6: ${t.typography.heading.fontSize.h6},
      },
    },
  },

  // Spacing — page margins and gaps between elements
  spacing: {
    page: {
      marginTop: ${t.spacing.page.marginTop},
      marginRight: ${t.spacing.page.marginRight},
      marginBottom: ${t.spacing.page.marginBottom},
      marginLeft: ${t.spacing.page.marginLeft},
    },
    sectionGap: ${t.spacing.sectionGap},
    paragraphGap: ${t.spacing.paragraphGap},
    componentGap: ${t.spacing.componentGap},
  },

  // Page defaults
  page: {
    size: '${t.page.size}',
    orientation: '${t.page.orientation}',
  },
}`;
}
